server:
    port: 9000
spring:
    application:
        name: cards
    config:
        import:
            - "optional:configserver:http://localhost:8071/config"
    profiles:
        active:
            - qa            
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:h2:mem:cards
        driverClassName: org.h2.Driver
        username: sa
        password: ""
build:
    version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

