server:
    port: 8090
spring:
    application:
            name: loans
    config:
        import:
            - "application_prod.yml"
            - "application_qa.yml"
            - "configserver:http://localhost:8071/config"
    profiles:
        active:
            - qa
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:h2:mem:loans
        driverClassName: org.h2.Driver
        username: sa
        password: 
management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
