spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "15.0"

accounts:
  message: "Welcome to EazyBank Local accounts related QA APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384